### Working with NN Module

In [1]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

In [4]:
#Create dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

#call forward pass
model(features) #This triggers the forward pass

tensor([[0.5802],
        [0.5264],
        [0.5153],
        [0.4929],
        [0.5789],
        [0.5574],
        [0.6042],
        [0.5043],
        [0.5262],
        [0.4510]], grad_fn=<SigmoidBackward0>)

In [7]:
print(model.linear.bias)
print(model.linear.weight)

Parameter containing:
tensor([-0.0590], requires_grad=True)
Parameter containing:
tensor([[-0.2117, -0.0763,  0.1818,  0.4361, -0.0203]], requires_grad=True)


In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary

In [10]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
#NN with hidden layers
class Model2(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out

In [14]:
model2 = Model2(features.shape[1])
model2(features)

tensor([[0.4976],
        [0.4875],
        [0.4754],
        [0.4722],
        [0.4813],
        [0.4590],
        [0.4735],
        [0.4835],
        [0.4702],
        [0.4734]], grad_fn=<SigmoidBackward0>)

In [17]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.0238, -0.0614, -0.1460,  0.3487,  0.1840],
        [-0.2633,  0.3785,  0.2300,  0.1860, -0.3017],
        [ 0.0464,  0.4451,  0.4365,  0.1574,  0.0465]], requires_grad=True)

In [18]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [19]:
#NN with sequential container
class Model3(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self,features):
        out = self.network(features)
        
        return out

In [20]:
model3 = Model3(features.shape[1])
model3(features)

tensor([[0.5742],
        [0.6064],
        [0.5867],
        [0.6036],
        [0.5819],
        [0.5927],
        [0.5904],
        [0.5941],
        [0.5907],
        [0.6125]], grad_fn=<SigmoidBackward0>)