### Working with Tensors

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.3.1


In [9]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#Get the dimension of the tensor
scalar.ndim

0

In [ ]:
#Get the item from tensor as python integer
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([1,2,3])
print(vector)
print(vector.ndim) #Number of square bracket (count onlu starting or ending)
print(vector.shape) #Number of elements inside the vector

tensor([1, 2, 3])
1
torch.Size([3])


In [23]:
#Matrix
matrix = torch.tensor([[1,2],
                      [3,4]])
print(matrix)
print(matrix.ndim)
print(matrix[0])
print(matrix[1])
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [33]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])
print(tensor[0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])


### Random tensors

In [35]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3468, 0.6722, 0.5992, 0.3219],
        [0.1601, 0.0626, 0.7661, 0.3868],
        [0.4544, 0.1254, 0.4808, 0.9564]])

In [40]:
random_tensor_2 = torch.rand(2)
random_tensor_2

tensor([0.1072, 0.8883])

In [ ]:
random_tensor_3 = torch.rand(2,3,4)
print(random_tensor_3)
print(random_tensor_3.ndim)

(tensor([[[0.2416, 0.2582, 0.6599, 0.1752],
          [0.5051, 0.7832, 0.7357, 0.5569],
          [0.2454, 0.3947, 0.8126, 0.3088]],
 
         [[0.4866, 0.1454, 0.2963, 0.0966],
          [0.7107, 0.7540, 0.7458, 0.8730],
          [0.8940, 0.9257, 0.8744, 0.5184]]]),
 3)

In [47]:
#Random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,244)) #color channel,height, width

print(random_image_size_tensor)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

tensor([[[0.8260, 0.9153, 0.3725,  ..., 0.8114, 0.4444, 0.0696],
         [0.2426, 0.4022, 0.8972,  ..., 0.1011, 0.2704, 0.6388],
         [0.7789, 0.2395, 0.9762,  ..., 0.8589, 0.5137, 0.5164],
         ...,
         [0.9039, 0.6295, 0.0191,  ..., 0.7965, 0.9291, 0.4755],
         [0.1098, 0.2414, 0.5594,  ..., 0.0245, 0.4238, 0.8658],
         [0.6981, 0.1008, 0.0996,  ..., 0.9551, 0.1795, 0.9501]],

        [[0.5570, 0.2164, 0.5899,  ..., 0.3498, 0.8689, 0.9090],
         [0.5262, 0.6854, 0.7448,  ..., 0.9883, 0.4154, 0.1979],
         [0.1734, 0.6920, 0.1611,  ..., 0.5126, 0.2120, 0.7009],
         ...,
         [0.6428, 0.3378, 0.5963,  ..., 0.4069, 0.7386, 0.4111],
         [0.9596, 0.9402, 0.1366,  ..., 0.7944, 0.6234, 0.1710],
         [0.6246, 0.0112, 0.1196,  ..., 0.1108, 0.3297, 0.9148]],

        [[0.9555, 0.0619, 0.6867,  ..., 0.7964, 0.0923, 0.8377],
         [0.5075, 0.2940, 0.6881,  ..., 0.4576, 0.1072, 0.0794],
         [0.7385, 0.1914, 0.7593,  ..., 0.8026, 0.1249, 0.

### Zeros and Ones

In [50]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
print(random_tensor)
print(zeros)
print(zeros*random_tensor)

tensor([[0.3468, 0.6722, 0.5992, 0.3219],
        [0.1601, 0.0626, 0.7661, 0.3868],
        [0.4544, 0.1254, 0.4808, 0.9564]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [53]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
random_tensor.dtype

torch.float32